apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm_chart.fullname" . }}
  labels:
    {{- include "helm_chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm_chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ .Values.configMaps | toJson |  sha256sum }}
        checksum/secrets: {{ .Values.secrets | toJson |  sha256sum }}
      labels:
        {{- include "helm_chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ tpl .Values.image.repository $ }}:{{ tpl .Values.image.tag $ | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          livenessProbe:
            {{- with .Values.initialDelaySeconds }}
            initialDelaySeconds: {{ . }}
            {{- end }}
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            {{- with .Values.initialDelaySeconds }}
            initialDelaySeconds: {{ . }}
            {{- end }}
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          {{- with .Values.run }}
          {{- tpl (toYaml .) $ | nindent 10 }}
          {{- end }}
          {{- with .Values.env }}
          env:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes}}
      volumes:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
