scicatEndpoint: http://backend-next.scicat-production

duo_facilities:
 - name: pgroups
   schedule: 0 2 * * 4
 - name: sls
   schedule: 0 3 * * 1,3,5
   ttlSecondsAfterFinished: 345600 # 4 (3+1 of buffer) days
 - name: swissfel
   schedule: 0 4 * * 1,3,5
   ttlSecondsAfterFinished: 345600 # 4 (3+1 of buffer) days
 - name: smus
   schedule: 0 5 * * 4
 - name: sinq
   schedule: 0 3 * * 6
 - name: sinq
   year: 2022
   schedule: 45 3 * * 6
 - name: sinq
   year: 2021
   schedule: 15 3 * * 6
 - name: sinq
   year: 2020
   schedule: 30 3 * * 6
