scicatEndpoint: http://backend.scicat-qa/api/v3

duo_facilities:
 - name: pgroups
   schedule: 0 2 * * 2
 - name: sls
   schedule: 30 3 * * 1,3,5
 - name: swissfel
   schedule: 30 4 * * 1,3,5
 - name: smus
   schedule: 0 5 * * 2
 - name: sinq
   schedule: 0 2 * * 6
 - name: sinq
   year: 2022
   schedule: 45 2 * * 6
 - name: sinq
   year: 2021
   schedule: 15 2 * * 6
 - name: sinq
   year: 2020
   schedule: 30 2 * * 6
