# Default values for search-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ""
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

nameOverride: ""
fullnameOverride: "catamel"

run:
  command: 
    - /bin/sh
  args: 
    - -c
    - >
      ls -al . ;
      ls -al server; cat server/config.json;
      echo "Environment: development";
      node --max-old-space-size=4096 .

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 3000

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: "scicat.fraction.ch"
      paths: 
        - path: "/api"
          pathType: Prefix
        - path: "/explorer"
          pathType: Prefix
        - path: "/auth"
          pathType: Prefix
  tls:
    - hosts:
      - "scicat.fraction.ch"
      secretName: "scicat-certificate"

env:
  - name: NODE_ENV
    value: development

volumes:
  - name: config-volume
    configMap:
      name: catamel-cm
  - name: catamel-secrets
    secret:
      secretName: catamel-s

volumeMounts:
  - name: config-volume
    mountPath: /usr/src/app/server/config.local.js
    subPath: config.local.js
  - name: config-volume
    mountPath: /usr/src/app/server/middleware.development.json
    subPath: middleware.development.json
  - name: config-volume
    mountPath: /usr/src/app/server/boot/login-callbacks.js
    subPath: login-callbacks.js
  - name: catamel-secrets
    mountPath: /usr/src/app/server/providers.json
    subPath: providers.json
  - name: catamel-secrets
    mountPath: /usr/src/app/server/datasources.development.json
    subPath: datasources.json
  - name: catamel-secrets
    mountPath: /usr/src/app/server/datasources.json
    subPath: datasources.json
  - name: catamel-secrets
    mountPath: /usr/src/app/server/functionalAccounts.json
    subPath: functionalAccounts.json
  - name: catamel-secrets
    mountPath: /usr/src/app/server/component-config.development.json
    subPath: component-config.json
