envValue: production

doiPrefix: "10.16907"

host: dacat.psi.ch

probeChecksEnabled: false

replicaCount: 1

ingress:
  enabled: false

run:
  command: 
    - /bin/sh
  args: 
    - -c
    - >
      sleep infinity
