baseUrl: http://backend-next.scicat-development/api/v3
panetBaseUrl: http://pan-ontologies-api.scicat-development
pssBaseUrl: http://pss.scicat-development

host: scicat.development.psi.ch

ingress:
  tls:
    - hosts:
      - "{{ .Values.host }}"
      secretName: "scicat-be-next-certificate"
