replicaCount: 1

image:
  repository: "{{ .Values.ciRepository }}"
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "{{ .Values.ciTag }}"

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 80

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: "{{ .Values.host }}"
      paths: 
        - path: "/"
          pathType: Prefix
  tls:
    - hosts:
      - "{{ .Values.host }}"
      secretName: "scicat-fe-certificate"

volumes:
  - name: config-volume
    configMap:
      name: "{{ .Release.Name }}-cm"
  - name: downloaddir
    emptyDir: {}

probeChecks:
  initialDelaySeconds: 480

configMaps: 
  "{{ .Release.Name }}-cm":
    environment.ts: "{{ .Values.ciVars.ENVIRONMENT }}"
    keycloak-icon-256px.svg: "{{ .Values.ciVars.KEYCLOAK_ICON }}"
    styles.scss: "{{ .Values.ciVars.STYLES }}"
    login.component.html: "{{ .Values.ciVars.LOGIN_COMPONENT }}"
    help.component.html: "{{ .Values.ciVars.HELP_COMPONENT }}"

initContainers:
  - name: install
    image: busybox
    command:
      - wget
      - "-O"
      - "/download-dir/site.png"
      - https://raw.githubusercontent.com/paulscherrerinstitute/scicat-ci/main/helm_configs/frontend/site.png
    volumeMounts:
      - name: downloaddir
        mountPath: "/download-dir"

volumeMounts:
  - name: config-volume
    mountPath: /usr/src/app/src/environments/{{ .Values.envFile }}
    subPath: environment.ts
  - name: config-volume
    mountPath: /usr/src/app/src/assets/images/keycloak_icon_256px.svg
    subPath: keycloak-icon-256px.svg
  - name: config-volume
    mountPath: /usr/src/app/src/styles.scss
    subPath: styles.scss
  - name: config-volume
    mountPath: /usr/src/app/src/app/users/login/login.component.html
    subPath: login.component.html
  - name: config-volume
    mountPath: /usr/src/app/src/app/help/help/help.component.html
    subPath: help.component.html
  - name: downloaddir
    mountPath: /usr/src/app/src/assets/images/site.png
    subPath: site.png

env:
  - name: env
    value: "{{ .Values.envValue }}"
