name: build-deploy

on:  
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  RELEASE_NAME: scicat-be
  TAG: ${{ github.event.pull_request.head.sha }}
  HOST: scicat.development.psi.ch

jobs:

  set_env: 
    uses: ./.github/workflows/environment.yml

  build:
    needs: set_env
    uses: ./.github/workflows/build.yml
    with: 
      context: backend/.
      registry: ghcr.io
      image_name: ${{ github.repository }}
      tag: ${{ needs.set_env.outputs.tag }}
      push_condition: ${{ github.event_name == 'pull_request' }}

  deploy:

    runs-on: ubuntu-latest
    environment: ${{ needs.set_env.outputs.environment }}
    needs: 
      - set_env
      - build

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set helm configmaps
      id: helm_configmaps
      run: |
        configMaps=$(cat <<EOF
          {
            "CONFIG_LOCAL": $(jq -R -s < helm_configs/${{ needs.set_env.outputs.environment }}/catamel_cm/config.local.js),
            "LOGIN_CALLBACKS": $(jq -R -s < helm_configs/${{ needs.set_env.outputs.environment }}/catamel_cm/login-callbacks.js),
            "MIDDLEWARE": $(jq -R -s < helm_configs/${{ needs.set_env.outputs.environment }}/catamel_cm/middleware.development.json)
          }
        EOF
        )
        echo "::set-output name=configMaps::$(echo $configMaps)"
    - name: Deploy to k8s using helm
      id: helm-deploy
      uses: 'glopezep/helm@v1.7.1'
      with:
        release: '${{ env.RELEASE_NAME }}'
        namespace: 'scicat-${{ needs.set_env.outputs.environment }}'
        chart: 'generic_service_chart'
        helm: helm3
        values: |
         ciRepository: ghcr.io/${{ github.repository }}
         ciTag: ${{ needs.set_env.outputs.tag }}
         ciVars: ${{ inputs.helm_ci_vars }}
        value-files: "helm_configs/${{ needs.set_env.outputs.environment }}/values.yaml"
        secrets: '${{ toJSON(secrets) }}'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
